name: hello

on: [push]

jobs:
  build:
    run-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v1
      - name: run a one-line script
        run: echo Hello World!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
